os:
  - "linux"
sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r ./requirements/ci.txt
  - pip install .
script:
  - py.test --verbose ./candv ./tests --cov ./candv ./tests
notifications:
  email: false
